"""
Analyzes resource coverage by neighborhood and category using SQL queries
against the database built by build_database.py.

Run after build_database.py: python scripts/analyze_gaps.py

Outputs:
  data/gap_analysis_summary.csv  - resource counts by neighborhood x category
  web/data.json                  - full resource list, used by the locator web app
"""
import sqlite3
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "database" / "community_resources.db"
SUMMARY_CSV = ROOT / "data" / "gap_analysis_summary.csv"
WEB_JSON = ROOT / "web" / "data.json"
WEB_JS = ROOT / "web" / "data.js"

CATEGORIES = [
    "Refugee & Immigration Services",
    "Multi-Service Community Center",
    "Education & ESL",
    "Healthcare",
    "Food Assistance",
]

FOCUS_NEIGHBORHOODS = ["Gulfton", "Alief", "Spring Branch", "Sharpstown"]


def run_analysis():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    # Resource count by neighborhood and category
    counts = cur.execute("""
        SELECT neighborhood, category, COUNT(*) as resource_count
        FROM resources
        GROUP BY neighborhood, category
        ORDER BY neighborhood, category
    """).fetchall()

    # Total resources per focus neighborhood (excluding citywide programs,
    # since those serve everyone and don't reflect local density)
    local_totals = cur.execute("""
        SELECT neighborhood, COUNT(*) as total
        FROM resources
        WHERE neighborhood != 'Citywide'
        GROUP BY neighborhood
        ORDER BY total DESC
    """).fetchall()

    # Coverage gaps: focus neighborhoods (high immigrant/refugee population per
    # neighborhood_context) that have zero direct-presence resources in a category.
    # Citywide programs are counted separately since they technically cover every
    # neighborhood, just without a local physical presence.
    gaps = []
    for neighborhood in FOCUS_NEIGHBORHOODS:
        present = {row["category"] for row in counts if row["neighborhood"] == neighborhood}
        missing = [c for c in CATEGORIES if c not in present]
        for category in missing:
            gaps.append({"neighborhood": neighborhood, "missing_category": category})

    # Write summary CSV
    with open(SUMMARY_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["neighborhood", "category", "resource_count"])
        for row in counts:
            writer.writerow([row["neighborhood"], row["category"], row["resource_count"]])

    # Export full resource list as JSON for the web app
    resources = cur.execute("SELECT * FROM resources ORDER BY category, name").fetchall()
    resources_list = [dict(r) for r in resources]
    context = cur.execute("SELECT * FROM neighborhood_context").fetchall()
    context_list = [dict(r) for r in context]

    payload = {"resources": resources_list, "neighborhood_context": context_list}

    WEB_JSON.parent.mkdir(exist_ok=True)
    with open(WEB_JSON, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)

    # Also emit as a plain JS file so web/index.html can load it via <script src="data.js">
    # and work when the file is opened directly (file://), without CORS issues from fetch().
    with open(WEB_JS, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/analyze_gaps.py - do not edit by hand\n")
        f.write(f"const RESOURCE_DATA = {json.dumps(payload, indent=2)};\n")

    conn.close()

    print("=== Resources per neighborhood (excluding citywide programs) ===")
    for row in local_totals:
        print(f"  {row['neighborhood']:<20} {row['total']}")

    print("\n=== Coverage gaps in focus neighborhoods (no local provider in category) ===")
    if gaps:
        for g in gaps:
            print(f"  {g['neighborhood']:<15} missing local presence: {g['missing_category']}")
    else:
        print("  No gaps found among focus neighborhoods.")

    print(f"\nSummary written to {SUMMARY_CSV}")
    print(f"Web app data written to {WEB_JSON} and {WEB_JS}")


if __name__ == "__main__":
    run_analysis()
